In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
en = pd.DataFrame(pd.read_csv('Data\WELFake_Dataset.csv'))
en=en[['title', 'text', 'label']]

en['label'] = en['label'].replace(0, 2)
en['label'] = en['label'].replace(1, 0)
en['label'] = en['label'].replace(2, 1)

en.head()

# Switch the numbers so now 1 = fake, 0 = real

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,0
1,NaN,Did they post their votes for Hillary already?,0
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",0
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,1
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",0

In [3]:
# merge title and text

def merge_title_content(df, title, content):
    df[title] = df[title].fillna('')
    df[content] = df[content].fillna('')
    df['merged_text'] =  df[title] + " " + df[content]

In [4]:
merge_title_content(en, 'title', 'text')
en_merged = en[['label', 'merged_text']]
en_merged.head()

   label                                        merged_text
0      0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1      0     Did they post their votes for Hillary already?
2      0  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3      1  Bobby Jindal, raised Hindu, uses story of Chri...
4      0  SATAN 2: Russia unvelis an image of its terrif...

In [40]:
# label count: real vs. fake 

en_label_count = en_merged['label'].value_counts()
en_label_latex = en_label_count.to_latex()

# convert to latex
en_label_latex

'\\begin{tabular}{lr}\n\\toprule\n & count \\\\\nlabel &  \\\\\n\\midrule\n0 & 37106 \\\\\n1 & 35028 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [41]:
en_label_count

label
0    37106
1    35028
Name: count, dtype: int64

In [42]:
cn = pd.DataFrame(pd.read_csv('Data\mcfend.csv'))

cn.head()

,news_id,publish_time,platform,check_time,label,url,title,content,pic_url,hashtag
0,news_plf01A00001,2023/2/2,中国互联网联合辟谣平台,2023/2/2,谣言,NaN,离婚窗口排长队,NaN,NaN,NaN
1,news_plf01A00002,2023/2/1,中国互联网联合辟谣平台,2023/2/2,谣言,NaN,哈工程教学楼地下有数门“超电磁炮”,NaN,NaN,NaN
2,news_plf01A00003,2023/2/1,中国互联网联合辟谣平台,2023/2/2,谣言,NaN,薯片胀袋是变质了,NaN,NaN,NaN
3,news_plf01A00004,2023/1/31,中国互联网联合辟谣平台,2023/2/2,谣言,NaN,成本只要1毛钱的人造鸡蛋泛滥,NaN,NaN,NaN
4,news_plf01A00005,2023/1/30,中国互联网联合辟谣平台,2023/2/2,谣言,NaN,隔着玻璃晒太阳能补钙,NaN,NaN,NaN

In [43]:
cn['label'] = cn['label'].replace('谣言', 1)
cn['label'] = cn['label'].replace('事实', 0)
cn = cn[cn['label'] != '尚无定论']

# drop unnecessary columns
cn = cn[['label', 'title', 'content']]

cn.head()

  label              title content
0     1            离婚窗口排长队     NaN
1     1  哈工程教学楼地下有数门“超电磁炮”     NaN
2     1           薯片胀袋是变质了     NaN
3     1     成本只要1毛钱的人造鸡蛋泛滥     NaN
4     1         隔着玻璃晒太阳能补钙     NaN

In [44]:
cn_cont = cn[cn['content'].notna()]
cn_cont.head()

,label,title,content
8144,0,青少年妈妈明星珍妮尔·埃文斯的婚纱在这里售价2999美元,2023年3月23日 · 青少年妈妈明星 Jenelle Evans 在周三发布到她的 In...
8145,0,凯莉·詹纳拒绝就《凯莉的一生》讨论泰加,2020年2月23日 · 2018年詹纳才20岁（她在8月满21岁），同时也是个非常年轻的母...
8146,0,奎因帕金斯,2023年3月30日 · 虎扑03月30日讯 今日步行者官方宣布，球队正式裁掉后卫特雷夫林-...
8147,0,席琳·迪翁向拉斯维加斯枪击案受害者捐赠音乐会收益,2021年11月10日 · 今年10月下旬，席琳·迪翁亲自宣布，由于健康问题，她原定于11月...
8148,0,Chris Evans、Millie Bobby Brown、Snoop Dogg等明星为被...,"IMDb, the world's most popular and authoritati..."

In [45]:

merge_title_content(cn_cont, 'title', 'content')
cn_merged = cn_cont[['label', 'merged_text']]
cn_merged.head()

     label                                        merged_text
8144     0  青少年妈妈明星珍妮尔·埃文斯的婚纱在这里售价2999美元 2023年3月23日 · 青少年妈...
8145     0  凯莉·詹纳拒绝就《凯莉的一生》讨论泰加 2020年2月23日 · 2018年詹纳才20岁（她...
8146     0  奎因帕金斯 2023年3月30日 · 虎扑03月30日讯 今日步行者官方宣布，球队正式裁掉后...
8147     0  席琳·迪翁向拉斯维加斯枪击案受害者捐赠音乐会收益 2021年11月10日 · 今年10月下旬...
8148     0  Chris Evans、Millie Bobby Brown、Snoop Dogg等明星为被...

In [46]:
# real fake distribution for CN

cn_label_count = cn_merged['label'].value_counts()
cn_label_latex = cn_label_count.to_latex()

# convert to latex
cn_label_latex

'\\begin{tabular}{lr}\n\\toprule\n & count \\\\\nlabel &  \\\\\n\\midrule\n1 & 10229 \\\\\n0 & 5601 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [47]:
cn_label_count

label
1    10229
0     5601
Name: count, dtype: int64

In [48]:
jp1 = pd.read_csv('Data\jpfake_news.csv')
jp1 = jp1[['context','isfake']]

# 0 = original/human-made
# 1 = partially generated
# 2 = completely generated 
# for the sake of this research I will presume all human-made news are factually correct, and i will replace all 1's and 2's as fake 

jp1['isfake'] = jp1['isfake'].replace([1,2],1)


jp1 = jp1.rename(columns = {'context' : 'merged_text', 
                      'isfake' : 'label'})
jp1.head()

                                         merged_text  label
0  朝日新聞など各社の報道によれば、宅配便最大手「ヤマト運輸」が日本郵政公社を相手取り、大手コン...      0
1  11月5日の各社報道によると、諫早湾干拓事業は諫早海人（諫早湾の「海」）に囲まれる大洋に位置...      1
2  産経新聞、中日新聞によると、2004年から2005年まで、この大会による3年おきの開催を、2...      1
3  開催地のリオデジャネイロ市に対して、大会期間中のリオデジャネイロオリンピックに関する公式発表...      1
4  毎日新聞・時事通信によると、2006年2月13日には、グッドウィル・グッゲンハイム・アン・ハ...      1

In [50]:
jp1_label_count = jp1['label'].value_counts()
jp1_label_count

label
1    9355
0    3685
Name: count, dtype: int64

In [8]:
## IMPORTANT - the above JP dataset has only one column for context (hence no column for title) might have to consider combining title and content for other language resources

In [53]:
jp2_label = pd.read_csv('Data\J-fakenews_v1\Label\label.tsv', sep='\t')
jp2_label.head()

,ID,Article,URL,Q1,Q2-1,Q2-2A,Q2-2B,Q4,Q5,Q6,Q7
0,1,[FactCheck] ｢3〜5歳児全ての幼児教育､保育を無償化｣は本当か？ー臨時国会所信表...,https://infact.press/2019/10/post-3413/,Inaccurate,"3:No, probably",-,2:Inadequate understanding,3.Neither/No such intention,2.Partisan,1.33,4.Threat correct understanding of politics and...
1,2,[FactCheck] ｢CNNが発砲した男の写真を加工し､白人に見せかけた｣との虚偽情報 ...,https://infact.press/2020/06/post-6452/,Pants-on-Fire,"3:No, probably",-,1.Trusting other sources,2.Denigration,3.Propaganda,4.00,6.Prejudice against national and racial
2,3,[FactCheck] ｢トランプ大統領の所得税が少なかった理由は多額の寄付｣との根拠不明情...,https://infact.press/2020/10/post-9190/,Unknown-Evidence,"3:No, probably",-,1.Trusting other sources,1.Flattery,2.Partisan,2.00,"3.Threat honor and trust in people, company an..."
3,4,[FactCheck] ｢ペンシルベニア州 2万1000人の死者名で郵便投票があったと提訴｣...,https://infact.press/2020/11/post-9692/,Misleading,"3:No, probably",-,3.Misleading,2.Denigration,2.Partisan,2.33,"3.Threat honor and trust in people, company an..."
4,5,[FactCheck] ｢北海道の中国人技能実習生は1万人以上｣｢占冠村人口の3割以上が中国...,https://infact.press/2020/10/post-9378/,Inaccurate,"4:No, definetely",-,2:Inadequate understanding,2.Denigration,3.Propaganda,2.33,6.Prejudice against national and racial

In [54]:
jp2_label['Q1'].unique()

<StringArray>
[        'Inaccurate',      'Pants-on-Fire',   'Unknown-Evidence',
         'Misleading',              'False',          'Half-True',
 'Suspended-Judgment',               'True']
Length: 8, dtype: str

In [55]:
jp2_label['Q1'].value_counts()

Q1
False                 153
Misleading             52
Inaccurate             50
Unknown-Evidence       30
Pants-on-Fire          16
Half-True               4
Suspended-Judgment      1
True                    1
Name: count, dtype: int64

In [56]:
# for the sake of this research I will drop the suspended-judgment, unknown evidence, true category, treat the rest as misinformation. 

jp2 = jp2_label[['Article', 'Q1']]
jp2 = jp2[~jp2['Q1'].isin(['Unknown-Evidence', 'Suspended-Judgment'])]

jp2['Q1'] = jp2['Q1'].replace(['False', 'Misleading', 'Pants-on-Fire', 'False', 'Half-True', 'Inaccurate'], 1)
jp2['Q1'] = jp2['Q1'].replace('True', 0)

jp2 = jp2.rename(columns = {'Article' : 'merged_text', 
                      'Q1' : 'label'})
jp2['merged_text'] = jp2['merged_text'].str.replace('[FactCheck]', '')

jp2.head()

                                         merged_text label
0            ｢3〜5歳児全ての幼児教育､保育を無償化｣は本当か？ー臨時国会所信表明の検証①     1
1           ｢CNNが発砲した男の写真を加工し､白人に見せかけた｣との虚偽情報 日本でも拡散     1
3   ｢ペンシルベニア州 2万1000人の死者名で郵便投票があったと提訴｣はミスリード　訴えは根...     1
4           ｢北海道の中国人技能実習生は1万人以上｣｢占冠村人口の3割以上が中国人｣は不正確     1
5        ｢台湾の防空システムが中国戦闘機を撃墜｣は虚偽 台湾当局の全面否定を中国メディアも追認     1

In [57]:
jp2_label_count = jp2['label'].value_counts()
jp2_label_count

label
1    275
0      1
Name: count, dtype: int64

In [58]:
jp = pd.concat([jp1, jp2], ignore_index=True)
jp.head()

                                         merged_text label
0  朝日新聞など各社の報道によれば、宅配便最大手「ヤマト運輸」が日本郵政公社を相手取り、大手コン...     0
1  11月5日の各社報道によると、諫早湾干拓事業は諫早海人（諫早湾の「海」）に囲まれる大洋に位置...     1
2  産経新聞、中日新聞によると、2004年から2005年まで、この大会による3年おきの開催を、2...     1
3  開催地のリオデジャネイロ市に対して、大会期間中のリオデジャネイロオリンピックに関する公式発表...     1
4  毎日新聞・時事通信によると、2006年2月13日には、グッドウィル・グッゲンハイム・アン・ハ...     1

In [63]:
en_merged.to_csv('data/en.csv', index = False)
cn_merged.to_csv('data/cn.csv', index = False)
jp.to_csv('data/jp.csv', index = False)

In [64]:
en_merged['label'].value_counts()

label
0    37106
1    35028
Name: count, dtype: int64

In [65]:
cn_merged['label'].value_counts()

label
1    10229
0     5601
Name: count, dtype: int64

In [62]:
jp['label'].value_counts()

label
1    9630
0    3686
Name: count, dtype: int64